import prisma from '../config/prisma.js';
import { generateInsuranceQuote } from '../services/pricingEngine.js';
import { fetchVehicleGovData, mapVehicleGovFields } from '../services/vehicleGovService.js';

/** Helper: coerce a value to string or undefined */
const str = (v: any): string | undefined =>
  v != null && v !== '' ? String(v) : undefined;

export const LeadModel = {
  getLeads: async (agentId?: string) => {
    return prisma.lead.findMany({
      where: agentId ? { agentId } : undefined,
      orderBy: {
        createdAt: 'desc',
      },
      include: {
        agent: { select: { id: true, name: true, email: true } },
      },
    });
  },

  getLeadById: async (id: string) => {
    return prisma.lead.findUnique({
      where: { id },
      include: {
        agent: { select: { id: true, name: true, email: true } },
      },
    });
  },

  createLead: async (input: any, agentId: string) => {
    // Handle array payload — take first element
    const raw = Array.isArray(input) ? input[0] : input;

    // Look up the vehicle in the Israeli gov registry server-side (avoids exposing our auth token to a third-party domain)
    const vehicleNumber = raw.vehicle_number || raw.misparRechev || raw.mispar_rechev;
    const v = vehicleNumber ? await fetchVehicleGovData(vehicleNumber) : {};
    const d = { ...raw, ...v };

    const quote = await generateInsuranceQuote(Number(d.age));

    const leadNationalIdRaw = d.lead_national_id ?? d.leadNationalId;
    const leadNationalId = leadNationalIdRaw != null && leadNationalIdRaw !== '' ? Number(leadNationalIdRaw) : undefined;

    const created = await prisma.lead.create({
      data: {
        leadNationalId,
        leadName:             d.lead_name           || d.leadName,
        phoneNumber:          d.phone_number         || d.phoneNumber,
        pdfUrl:               d.pdfUrl,
        agentId,

        // Person-specific fields
        age:                  str(d.age),
        dateOfBirth:          str(d.date_of_birth    || d.dateOfBirth),
        cost:                 str(d.cost             || d.cost_nis),
        yearOfLicenseIssued:  str(d.year_of_license_issued || d.yearOfLicenseIssued || d.license_issue_year),
        interestedIn:         (d.interested_in || d.interestedIn || undefined) as any,

        // Insurance quote pricing
        mandatoryPrice:       quote.mandatoryPrice,
        thirdPartyPrice:      quote.thirdPartyPrice,
        complimentaryPrice:   quote.complimentaryPrice,

        // Vehicle info fields (snake_case from API → camelCase Prisma)
        ...mapVehicleGovFields(d),
      },
    });

    return LeadModel.updateLeadFlowStatus(created.id, 'QUOTE_READY', agentId, 'Quote auto-generated by pricing engine');
  },

  deleteLead: async (id: string) => {
    try {
      await prisma.lead.delete({
        where: { id },
      });
      return true;
    } catch (error) {
      // If it doesn't exist, prisma throws
      return null;
    }
  },

  updateLeadFlowStatus: async (id: string, leadFlowStatus: any, userId?: string, note?: string) => {
    return prisma.$transaction(async (tx) => {
      const existing = await tx.lead.findUnique({ where: { id } });
      if (!existing) throw new Error('Lead not found');

      const updated = await tx.lead.update({
        where: { id },
        data: { leadFlowStatus },
      });

      await tx.leadFlowStatusLog.create({
        data: {
          leadId: id,
          fromStatus: existing.leadFlowStatus,
          toStatus: leadFlowStatus,
          changedBy: userId,
          note,
        },
      });

      return updated;
    });
  },

  updateLeadAgent: async (id: string, agentId: string) => {
    return prisma.lead.update({
      where: { id },
      data: { agentId },
      include: {
        agent: { select: { id: true, name: true, email: true } },
      },
    });
  },

  updateLeadQuote: async (
    id: string,
    data: {
      mandatoryPrice?: number;
      thirdPartyPrice?: number;
      complimentaryPrice?: number;
      glassAndMoreSelected?: boolean;
      complementaryVipSelected?: boolean;
    }
  ) => {
    return prisma.lead.update({
      where: { id },
      data,
    });
  },

  updateLeadPricingPdfUrl: async (id: string, pricingPdfUrl: string) => {
    return prisma.lead.update({
      where: { id },
      data: { pricingPdfUrl },
    });
  },

  convertToCustomer: async (
    leadId: string,
    policyData: {
      policyNumber: string;
      policyType: string;
      type?: string | null;
      insuranceCompany: string;
      startDate?: string | null;
      endDate?: string | null;
    }
  ) => {
    return prisma.$transaction(async (tx) => {
      const lead = await tx.lead.findUnique({ where: { id: leadId } });
      if (!lead) throw new Error('Lead not found');

      const customer = await tx.customer.create({
        data: {
          customerNationalId: lead.leadNationalId,
          customerName: lead.leadName,
          idNumber: lead.idNumber,
          dateOfBirth: lead.dateOfBirth,
          agentId: lead.agentId,
          convertedFromLead: true,

          phoneNumber:          lead.phoneNumber,
          age:                  lead.age,
          cost:                 lead.cost,
          yearOfLicenseIssued:  lead.yearOfLicenseIssued,
          interestedIn:         lead.interestedIn,

          mandatoryPrice:       lead.mandatoryPrice,
          thirdPartyPrice:      lead.thirdPartyPrice,
          complimentaryPrice:   lead.complimentaryPrice,

          glassAndMoreSelected:     lead.glassAndMoreSelected,
          complementaryVipSelected: lead.complementaryVipSelected,

          contacts: lead.phoneNumber
            ? { create: [{ type: 'mobile', value: lead.phoneNumber, label: 'Mobile', icon: 'phone' }] }
            : undefined,
        },
      });

      // The lead represents (at most) one car pre-conversion; carry it over into its own Vehicle row.
      let vehicle = null;
      if (lead.misparRechev) {
        vehicle = await tx.vehicle.create({
          data: {
            customerId:           customer.id,
            misparRechev:         lead.misparRechev,
            tozeretCd:            lead.tozeretCd,
            sugDegem:             lead.sugDegem,
            tozeretNm:            lead.tozeretNm,
            degemCd:              lead.degemCd,
            shnatYitzur:          lead.shnatYitzur,
            degemNm:              lead.degemNm,
            ramatGimur:           lead.ramatGimur,
            ramatEivzurBetihuti:  lead.ramatEivzurBetihuti,
            kvutzatZihum:         lead.kvutzatZihum,
            tzevaCd:              lead.tzevaCd,
            tzevaRechev:          lead.tzevaRechev,
            zmigKidmi:            lead.zmigKidmi,
            zmigAhori:            lead.zmigAhori,
            sugDelekNm:           lead.sugDelekNm,
            horaatRishum:         lead.horaatRishum,
            moedAliyaLakvish:     lead.moedAliyaLakvish,
            baalut:               lead.baalut,
            misgeret:             lead.misgeret,
            tozeretEretzNm:       lead.tozeretEretzNm,
            mishkalKolel:         lead.mishkalKolel,
            nefahManoa:           lead.nefahManoa,
            kinuyMishari:         lead.kinuyMishari,
            mivchanAcharonDt:     lead.mivchanAcharonDt,
            tokefDt:              lead.tokefDt,
            taarichPkikaDt:       lead.taarichPkikaDt,
            taarichPkiah:         lead.taarichPkiah,
            kvuzatAgra:           lead.kvuzatAgra,
            mahozMoshav:          lead.mahozMoshav,
            sugRechevNm:          lead.sugRechevNm,
            degemManoa:           lead.degemManoa,
            koachSus:             lead.koachSus,
            misparDlatot:         lead.misparDlatot,
            misparMoshavim:       lead.misparMoshavim,
          },
        });
      }

      await tx.policy.create({
        data: {
          policyNumber:     policyData.policyNumber,
          policyType:       policyData.policyType,
          type:             policyData.type || null,
          insuranceCompany: policyData.insuranceCompany,
          carId:            policyData.policyType === 'Car' ? vehicle?.id ?? null : null,
          carNumber:        policyData.policyType === 'Car' ? vehicle?.misparRechev ?? null : null,
          manufacturer:     policyData.policyType === 'Car' ? vehicle?.tozeretNm ?? null : null,
          startDate:        policyData.startDate ? new Date(policyData.startDate) : null,
          endDate:          policyData.endDate ? new Date(policyData.endDate) : null,
          status:           'Active',
          customerId:       customer.id,
        },
      });

      await tx.lead.delete({ where: { id: leadId } });

      return tx.customer.findUnique({
        where: { id: customer.id },
        include: { contacts: true, policies: true, vehicles: true },
      });
    });
  },
};

